runtime: python39
entrypoint: gunicorn -b :$PORT EasyInventory.wsgi:application

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
    DJANGO_SECRET_KEY: "-l5kmkljlzk&^t+dt82xp=w%4cv!)23u5s1ouhuks6p3l^i4*h"
    ALLOWED_HOSTS: ""
