runtime: python39
entrypoint: gunicorn -b :$PORT EasyInventory.wsgi:application

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
    DJANGO_SECRET_KEY: "django-insecure-q4&-wr3g1e1qlyam+*)h2(p=u*j!f^v4^y7ny!_bj(65qsj$)="
    ALLOWED_HOSTS: ""
