runtime: python39
entrypoint: gunicorn -b :$PORT EasyInventory.wsgi:application

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
    DJANGO_SECRET_KEY: "your-secret-key"
    ALLOWED_HOSTS: "easyinventory-445001.uc.r.appspot.com"
