runtime: python39
entrypoint: gunicorn -b :$PORT your_project_name.wsgi:application

handlers:
- url: /static
  static_dir: static/

env_variables:
    DJANGO_SECRET_KEY: "your-secret-key"
    ALLOWED_HOSTS: "your-domain.com"
